"""
sql_agent.py

Role-aware Text-to-SQL retrieval against Postgres.

This module provides functions for:
- Generating a SQL query from natural language via Ollama (Llama 3.1)
- Restricting generated queries to an explicit allow-list of tables
- Executing read-only queries with a least-privilege database user

Example:
    rows, sql = retrieve_from_sql(RoleEnum.sales, "total sales last month")
"""
# ============================================================================
# Packages
# ============================================================================
# SQLAlchemy
from sqlalchemy import text

# LangChain Ollama
from langchain_ollama import ChatOllama

# Project Imports
from shared.config import settings
from shared.schemas.role import RoleEnum, ROLE_HAS_SQL_ACCESS
from shared.utils.postgres import get_db

# ============================================================================
# Exceptions
# ============================================================================
class RoleNotAuthorizedInSQLError(Exception):
    """Raised when a role has no access to the SQL retrieval tool."""


class UnsafeQueryError(Exception):
    """Raised when the generated SQL references a non-allowed table or statement."""

# ============================================================================
# Constants
# ============================================================================
ALLOWED_TABLES = {"reviews", "sales"}

FORBIDDEN_KEYWORDS = {"insert", "update", "delete", "drop", "alter", "truncate", "grant"}

SQL_GENERATION_PROMPT = """You are a PostgreSQL expert.

Given the user question, write a single read-only SQL SELECT query.
Only use these tables: reviews(date, rating, review_title, review_content),
bakery_sales_data(date, order_id, item_name, item_price, quantity, transaction_type, time_of_sale, transaction_amount).
Return ONLY the SQL query, no explanation, no markdown formatting.

Question: {question}
SQL query:"""

# engine = create_engine(
#     f"postgresql+psycopg2://{settings.postgres_user}:{settings.postgres_password}"
#     f"@{settings.postgres_host}:{settings.postgres_port}/{settings.postgres_db}"
# )

llm = ChatOllama(model="llama3.1", base_url=settings.ollama_base_url, temperature=0)

# ============================================================================
# Helpers
# ============================================================================
def validate_sql(sql: str) -> None:
    """Validate that a generated SQL query is safe and within scope.

    Args:
        sql: SQL query string generated by the LLM.

    Raises:
        UnsafeQueryError: If the query contains forbidden keywords or
            references tables outside the allow-list.
    """
    lowered = sql.lower()

    for keyword in FORBIDDEN_KEYWORDS:
        if keyword in lowered:
            raise UnsafeQueryError(f"Forbidden keyword detected: {keyword}")

    if not lowered.strip().startswith("select"):
        raise UnsafeQueryError("Only SELECT statements are allowed")

    # Defense in depth: also enforced at the database grant level
    if not any(table in lowered for table in ALLOWED_TABLES):
        raise UnsafeQueryError("Query does not reference any allowed table")
    
# ============================================================================
# Services
# ============================================================================
def retrieve_from_sql(role: RoleEnum, query: str) -> tuple[list[dict], str]:
    """Translate a natural language query into SQL and execute it.

    Args:
        role: Role of the requesting user, resolved upstream by backend.
        query: Natural language question about sales or reviews data.

    Returns:
        A tuple of (result rows as dicts, generated SQL string).

    Raises:
        RoleNotAuthorizedError: If the role has no SQL retrieval access.
        UnsafeQueryError: If the generated SQL fails safety validation.
    """
    if not ROLE_HAS_SQL_ACCESS.get(role, False):
        raise RoleNotAuthorizedInSQLError(f"Role '{role.value}' has no SQL retrieval access")

    prompt = SQL_GENERATION_PROMPT.format(question=query)
    response = llm.invoke(prompt)
    generated_sql = response.content.strip().strip("```sql").strip("```").strip()

    validate_sql(generated_sql)

    with get_db() as db:
        result = db.execute(text(generated_sql))
        rows = [dict(row._mapping) for row in result]

    return rows, generated_sql