"""
sql_agent.py

Role-aware Text-to-SQL retrieval against Postgres, orchestrated as a LangGraph.

This module provides functions for:
- Generating a SQL query from natural language via Ollama (Llama 3.1)
- Restricting generated queries to an explicit allow-list of tables
- Executing read-only queries with a least-privilege database user

Example:
    rows, sql = retrieve_from_sql(RoleEnum.sales, "total sales last month")
"""
# ============================================================================
# Packages
# ============================================================================
# SQLAlchemy
from sqlalchemy import create_engine, text

# LangChain Ollama
from langchain_ollama import ChatOllama

# LangGraph
from langgraph.graph import StateGraph, START, END

# Langfuse
from langfuse.decorators import observe, langfuse_context

# Project Imports
from shared.config.settings import settings
from shared.config.loader import load_agents
from shared.database.postgres import get_db
from shared.schemas.role import RoleEnum, ROLE_HAS_SQL_ACCESS
from rag_service.app.services.retrieval.sql_graph_state import SQLAgentState
from shared.observability.langfuse_client import get_langfuse_handler
from shared.observability.telemetry import get_current_otel_trace_id

agent_config = load_agents().get("sql_agent", None)

llm = None

if agent_config.get("provider", None) == "ollama":
    llm = ChatOllama(model=agent_config.get("model", None), base_url=settings.ollama_base_url, temperature=agent_config.get("temperature"))


# ============================================================================
# Exceptions
# ============================================================================
class RoleNotAuthorizedInSQLError(Exception):
    """Raised when a role has no access to the SQL retrieval tool."""


class UnsafeQueryError(Exception):
    """Raised when the generated SQL references a non-allowed table or statement."""

# ============================================================================
# Constants
# ============================================================================
ALLOWED_TABLES = {"reviews", "bakery_sales_data"}
FORBIDDEN_KEYWORDS = {"insert", "update", "delete", "drop", "alter", "truncate", "grant"}

SQL_GENERATION_PROMPT = load_agents().get("sql_generation_prompt", None).get("prompt", None)

# ============================================================================
# Helpers
# ============================================================================
def validate_sql(sql: str) -> None:
    """Validate that a generated SQL query is safe and within scope.

    Args:
        sql: SQL query string generated by the LLM.

    Raises:
        UnsafeQueryError: If the query contains forbidden keywords or
            references tables outside the allow-list.
    """
    lowered = sql.lower()

    for keyword in FORBIDDEN_KEYWORDS:
        if keyword in lowered:
            raise UnsafeQueryError(f"Forbidden keyword detected: {keyword}")

    if not lowered.strip().startswith("select"):
        raise UnsafeQueryError("Only SELECT statements are allowed")

    # Defense in depth: also enforced at the database grant level
    if not any(table in lowered for table in ALLOWED_TABLES):
        raise UnsafeQueryError("Query does not reference any allowed table")
    
# ============================================================================
# Graph Nodes
# ============================================================================
def generate_sql_node(state: SQLAgentState) -> SQLAgentState:
    """Generate a SQL query from the natural language question.

    Args:
        state: Current graph state.

    Returns:
        Updated state with generated_sql populated.
    """
    prompt = SQL_GENERATION_PROMPT.format(question=state["question"])
    response = llm.invoke(prompt)
    sql = response.content.strip().strip("```sql").strip("```").strip()
    return {**state, "generated_sql": sql}


def validate_sql_node(state: SQLAgentState) -> SQLAgentState:
    """Validate the generated SQL query against safety rules.

    Args:
        state: Current graph state.

    Returns:
        Updated state, with error populated if validation fails.
    """
    try:
        validate_sql(state["generated_sql"])
        return {**state, "error": None}
    except UnsafeQueryError as e:
        return {**state, "error": str(e)}


def execute_sql_node(state: SQLAgentState) -> SQLAgentState:
    """Execute the validated SQL query against Postgres.

    Args:
        state: Current graph state.

    Returns:
        Updated state with rows populated.
    """
    with get_db() as db:
        result = db.execute(text(state["generated_sql"]))
        rows = [dict(row._mapping) for row in result]
    return {**state, "rows": rows}


def _route_after_validation(state: SQLAgentState) -> str:
    """Route to execution or end the graph, depending on validation result.

    Args:
        state: Current graph state.

    Returns:
        The name of the next node, or END if validation failed.
    """
    return END if state["error"] else "execute_sql"
# ============================================================================
# Graph Definition
# ============================================================================
def _build_sql_graph():
    """Build and compile the SQL generation LangGraph.

    Returns:
        A compiled LangGraph ready to be invoked.
    """

    graph = StateGraph(SQLAgentState)

    graph.add_node("generate_sql", generate_sql_node)
    graph.add_node("validate_sql", validate_sql_node)
    graph.add_node("execute_sql", execute_sql_node)

    graph.add_edge(START, "generate_sql")
    graph.add_edge("generate_sql", "validate_sql")
    graph.add_conditional_edges("validate_sql", _route_after_validation)
    graph.add_edge("execute_sql", END)

    return graph.compile()


sql_agent_graph = _build_sql_graph()

# ============================================================================
# Services
# ============================================================================
@observe(name="rag_service/sql_generation")
def retrieve_from_sql(role: RoleEnum, query: str) -> tuple[list[dict], str]:
    """Translate a natural language query into SQL and execute it via LangGraph.

    Args:
        role: Role of the requesting user, resolved upstream by backend.
        query: Natural language question about sales or reviews data.

    Returns:
        A tuple of (result rows as dicts, generated SQL string).

    Raises:
        RoleNotAuthorizedError: If the role has no SQL retrieval access.
        UnsafeQueryError: If the generated SQL fails safety validation.
    """
    otel_trace_id = get_current_otel_trace_id()
    if otel_trace_id:
        langfuse_context.update_current_trace(
            metadata={"otel_trace_id": otel_trace_id, "role": role.value}
        )

    if not ROLE_HAS_SQL_ACCESS.get(role, False):
        raise RoleNotAuthorizedError(f"Role '{role.value}' has no SQL retrieval access")

    handler = get_langfuse_handler()
    initial_state: SQLAgentState = {
        "question": query,
        "role": role.value,
        "generated_sql": "",
        "rows": [],
        "error": None,
    }

    result = sql_agent_graph.invoke(
        initial_state,
        config={"callbacks": [handler]},
    )

    if result["error"]:
        raise UnsafeQueryError(result["error"])

    return result["rows"], result["generated_sql"]