"""
Chat API Tables 
"""

# ============================================================================
# Packages
# ============================================================================
# Pydantic
from pydantic import BaseModel

# Shared Imports
from shared.schemas.role import RoleEnum

# Typing
from typing import TypedDict

# ============================================================================
# Data Models
# ============================================================================

class ChatMessage(BaseModel):
    """Chat message schema."""

    role: str  # "user" or "assistant"
    content: str


class ChatRequest(BaseModel):
    """Chat request schema."""

    query: str
    session_id: str # LangGraph Thread ID


class ChatResponse(BaseModel):
    """Chat response schema."""

    answer: str
    sources: list = []
    route_used: str  # "vector_rag" | "sql_agent" | "denied" | etc.
    session_id: str # LangGraph Thread ID
    
class ChatState(TypedDict):
    """State passed between nodes of the main chat orchestration graph.

    Attributes:
        query: Natural language question from the user.
        role: Role of the requesting user, resolved from JWT upstream.
        route: Intent classification result ("vector" or "sql").
        context: Retrieved context, either text chunks or stringified rows.
        sources: Source identifiers (file names or generated SQL).
        answer: Final answer generated by the LLM.
    """
    query: str
    role: str
    route: str
    context: list[str]
    sources: list[str]
    answer: str